export interface ArrangementClip {
  id: string;
  lane: string;
  start: number;
  length: number;
  color: 'violet' | 'amber' | 'rose' | 'cyan' | 'blue' | 'green';
  label: string;
}

export interface ChannelTrack {
  id: string;
  name: string;
  icon: string;
  color: string;
  volume: number;
  pattern: boolean[];
}

export interface MixerStrip {
  id: string;
  name: string;
  color: string;
  level: number;
  pan: number;
}

export interface PianoNote {
  id: string;
  pitch: string;
  start: number;
  length: number;
}

export const arrangementClips: ArrangementClip[] = [
  {
    id: 'drums-1',
    lane: 'Drums',
    start: 1,
    length: 16,
    color: 'violet',
    label: 'Drum groove A',
  },
  {
    id: 'drums-2',
    lane: 'Drums',
    start: 17,
    length: 16,
    color: 'violet',
    label: 'Drum groove B',
  },
  {
    id: 'drums-3',
    lane: 'Drums',
    start: 33,
    length: 16,
    color: 'violet',
    label: 'Drum groove C',
  },
  {
    id: 'drums-4',
    lane: 'Drums',
    start: 49,
    length: 12,
    color: 'violet',
    label: 'Drum groove D',
  },
  {
    id: 'bass-1',
    lane: 'Bass',
    start: 1,
    length: 18,
    color: 'amber',
    label: 'Bass call',
  },
  {
    id: 'bass-2',
    lane: 'Bass',
    start: 37,
    length: 14,
    color: 'amber',
    label: 'Bass response',
  },
  { id: 'bass-3', lane: 'Bass', start: 59, length: 6, color: 'amber', label: 'Bass tag' },
  {
    id: 'chords-1',
    lane: 'Chords',
    start: 1,
    length: 20,
    color: 'rose',
    label: 'Warm stabs',
  },
  {
    id: 'chords-2',
    lane: 'Chords',
    start: 21,
    length: 14,
    color: 'rose',
    label: 'Chord lift',
  },
  {
    id: 'chords-3',
    lane: 'Chords',
    start: 43,
    length: 21,
    color: 'rose',
    label: 'Final phrase',
  },
  {
    id: 'melody-1',
    lane: 'Melody',
    start: 5,
    length: 18,
    color: 'cyan',
    label: 'Call melody',
  },
  {
    id: 'melody-2',
    lane: 'Melody',
    start: 43,
    length: 20,
    color: 'cyan',
    label: 'Answer melody',
  },
  {
    id: 'vocal-1',
    lane: 'Vocal',
    start: 1,
    length: 18,
    color: 'blue',
    label: 'Vocal chop',
  },
  {
    id: 'vocal-2',
    lane: 'Vocal',
    start: 21,
    length: 22,
    color: 'blue',
    label: 'Hook texture',
  },
  { id: 'fx-1', lane: 'FX', start: 2, length: 5, color: 'green', label: 'Rise' },
  { id: 'fx-2', lane: 'FX', start: 19, length: 7, color: 'green', label: 'Sweep' },
  { id: 'fx-3', lane: 'FX', start: 31, length: 8, color: 'green', label: 'Impact tail' },
];

export const channelTracks: ChannelTrack[] = [
  {
    id: 'kick',
    name: 'Kick',
    icon: '🥁',
    color: '#a855f7',
    volume: 72,
    pattern: [
      true,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      true,
      false,
    ],
  },
  {
    id: 'snare',
    name: 'Snare',
    icon: '🪘',
    color: '#c084fc',
    volume: 58,
    pattern: [
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
    ],
  },
  {
    id: 'clap',
    name: 'Clap',
    icon: '👏',
    color: '#ec4899',
    volume: 64,
    pattern: [
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
    ],
  },
  {
    id: 'hat',
    name: 'Hi Hat',
    icon: '✦',
    color: '#8b5cf6',
    volume: 48,
    pattern: [
      false,
      true,
      false,
      true,
      false,
      true,
      false,
      true,
      false,
      true,
      false,
      true,
      false,
      true,
      false,
      true,
    ],
  },
  {
    id: 'shaker',
    name: 'Shaker',
    icon: '✧',
    color: '#14b8a6',
    volume: 42,
    pattern: [
      false,
      false,
      true,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      true,
      false,
      false,
    ],
  },
  {
    id: 'bass',
    name: 'Bass',
    icon: '🎸',
    color: '#f59e0b',
    volume: 76,
    pattern: [
      true,
      false,
      false,
      true,
      false,
      false,
      true,
      false,
      false,
      true,
      false,
      false,
      true,
      false,
      false,
      false,
    ],
  },
  {
    id: 'piano',
    name: 'Piano',
    icon: '▦',
    color: '#f97316',
    volume: 52,
    pattern: [
      true,
      false,
      true,
      false,
      false,
      true,
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      true,
      false,
      false,
    ],
  },
  {
    id: 'chords',
    name: 'Chords',
    icon: '▤',
    color: '#fb7185',
    volume: 61,
    pattern: [
      true,
      true,
      false,
      false,
      true,
      true,
      false,
      false,
      true,
      true,
      false,
      false,
      true,
      false,
      true,
      false,
    ],
  },
  {
    id: 'lead',
    name: 'Lead',
    icon: '◆',
    color: '#22d3ee',
    volume: 55,
    pattern: [
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      true,
      false,
      true,
      false,
    ],
  },
  {
    id: 'strings',
    name: 'Strings',
    icon: '≈',
    color: '#2dd4bf',
    volume: 46,
    pattern: [
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
    ],
  },
];

export const mixerStrips: MixerStrip[] = [
  { id: 'kick', name: 'Kick', color: '#a855f7', level: 78, pan: -8 },
  { id: 'snare', name: 'Snare', color: '#c084fc', level: 64, pan: 6 },
  { id: 'bass', name: 'Bass', color: '#f59e0b', level: 72, pan: 0 },
  { id: 'chords', name: 'Chords', color: '#fb7185', level: 58, pan: -14 },
  { id: 'lead', name: 'Lead', color: '#22d3ee', level: 52, pan: 12 },
  { id: 'vocal', name: 'Vocal', color: '#60a5fa', level: 67, pan: 0 },
  { id: 'fx', name: 'FX', color: '#22c55e', level: 44, pan: 18 },
  { id: 'master', name: 'Master', color: '#f8fafc', level: 83, pan: 0 },
];

export const pianoNotes: PianoNote[] = [
  { id: 'n1', pitch: 'C4', start: 1, length: 2 },
  { id: 'n2', pitch: 'D#4', start: 3, length: 2 },
  { id: 'n3', pitch: 'G4', start: 5, length: 3 },
  { id: 'n4', pitch: 'A#3', start: 8, length: 2 },
  { id: 'n5', pitch: 'F4', start: 11, length: 4 },
  { id: 'n6', pitch: 'G#4', start: 16, length: 2 },
  { id: 'n7', pitch: 'C5', start: 19, length: 3 },
  { id: 'n8', pitch: 'A#4', start: 23, length: 2 },
  { id: 'n9', pitch: 'G4', start: 27, length: 4 },
  { id: 'n10', pitch: 'D#4', start: 32, length: 3 },
];

export const browserGroups = [
  {
    title: 'Library',
    items: ['Sounds', 'Instruments', 'Loops', 'Vocals', 'Samples', 'MIDI', 'Templates'],
  },
  {
    title: 'Academy',
    items: ['Lessons', 'Assignments', 'Challenges', 'Course Notes', 'Feedback'],
  },
  {
    title: 'Recent files',
    items: ['Afro House Groove', '3 Step Vibe', 'Trap Soul Beat', 'Piano Chords Idea'],
  },
];
